name: FTP Upload

on:                       # トリガーの設定
  push:                   # プッシュ時に実行
    branches: [main]    # ブランチの指定
      
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action   # 分かりやすいジョブの名前
    runs-on: ubuntu-latest    # 実行環境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0   # チェックアウトアクション（https://github.com/actions/checkout）
        
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4     # FTPアップロードアクション（https://github.com/SamKirkland/FTP-Deploy-Action）
        with:
          server: ${{ secrets.STAGING_SERVER }}       # FTPのサーバーアドレス
          username: ${{ secrets.STAGING_USERNAME }}   # FTPのユーザー名
          password: ${{ secrets.STAGING_PASSWORD }}   # FTPのパスワード
          protocol: ftps
          local-dir: sakefes-sendai2023/                          # アップロードしたいフォルダのパス
          server-dir: /home/ohagi0503/www/      # アップロード先のフォルダのパス
